### ISSUE TITLE
Bootloop on latest nightly (UbuntuTouch-20150310-bacon-NIGHTLY.zip)

### ISSUE THREAD

**Issue by jimdrie** [ubports/ubuntu-touch-for-oneplus-one#11]
The initial system.img worked fine (UbuntuTouch-20150302-bacon-DEV.zip) with Multirom (could be related, have not tested the new nightly without Multirom, but since booting goes fine I doubt it), but after replacing the system.img with the script provided, it gives a bootloop (although it takes quite some time for it to reboot). After a few times I managed to get a clean last_kmsg: http://pastebin.com/qD34W1Um

Probably irrelevant, but I executed all commands to install Ubuntu Touch from my laptop running Arch Linux.

**Comment by mariogrip** [comment]
Found the problem, it will be fix in the next nightly. Thanks for reporting! :)

**Comment by jimdrie** [comment]
The problem still seems to be in the last nightly (UbuntuTouch-20150311-bacon-NIGHTLY.zip): http://pastebin.com/4n2U90C9

**Comment by mariogrip** [comment]
This should fix that!

https://github.com/ubuntu-touch-oneplus-one/android_device_oneplus_bacon/commit/47fd110260dcef20723df21f3ea18d9943bafb26

Thanks for reporting

**Comment by cc52** [comment]
The problem still seems to be in the last nightly (UbuntuTouch-20150316-bacon-NIGHTLY.zip//UbuntuTouch-20150315.bacon-NIGHTLY.zip )

**Comment by jwestenberg** [comment]
UbuntuTouch-20150316-bacon-NIGHTLY.zip puts mine into a bootloop as well.

**Comment by mariogrip** [comment]
This should be fixed now, if not please reopen the issue.
